# Generated by Django 5.2 on 2025-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.CharField(default='This is a very good product, I would like to recommend it to everyone.', max_length=200),
        ),
    ]
